### ISSUE TITLE
Config dosya oluşturma hatası.

### ISSUE THREAD

**Issue by mekaercu** [aleynatasdemir/DeleteFilesApp#1]
Merhaba

Uygulamayı "DeleteFilesAppFramework **-createconfig**" parametresi ile çalıştırıldığında, config dosyasını oluşturuyor. Fakat diğer parametrelere göre de silme işlemine devam ediyor. 
Uygulama **-createconfig** parametresi ile çalıştırıldığında sadece config dosyasını oluşturmalı. Silme işlemini gerçekleştirmemeli.

**Comment by aleynatasdemir** [comment]
Merhaba,

Hatayı düzelttim ve düzeltilmiş kodu tekrar yükledim. Bunun dışında artık
argümanları alırken büyük/küçük harf duyarlılığı görmezden geliniyor.

İyi çalışmalar.

mekaercu ***@***.***>, 9 Ağu 2024 Cum, 11:00 tarihinde şunu
yazdı:
